### ISSUE TITLE
Add specific select2 helpers

### ISSUE THREAD

**Issue by Hirurg103** [Hirurg103/capybara_select2#12]
I am not sure if we need the test helpers below so I am asking for the community help.

Please add 👍  if you need the helpers or 👎  if you think they are not necessary

```ruby
# open select2 widget
select2_open css: '.select2'
select2_open label: 'Todo'

# close select2 widget
select2_close css: '.select2'
select2_close label: 'Todo'

# type into the search field within an opened select2 widget
select2_search 'Minsk'

# select an option from an opened select box
select2_select_option 'Buy Milk'
```

If you think that only some of the helpers above might be useful please add your opinion in the comments below

**Comment by fabianoarruda** [comment]
I think that a "close" helper would be very useful! for instance, in my tests with Capybara sometimes the select2 widget wont close after a selection is made; in some cases a test fail because the driver cant find a button obstructed by the widget :(  
I have to manually make capybara click on something else to make select2 widget go away.

**Comment by coliver** [comment]
These all look helpful. I'm hitting a situation where I need to type into the search and the result doesn't match exactly what I'm typing in. These would make it easier to select the option.

**Comment by Hirurg103** [comment]
Hi @fabianoarruda @coliver , thank you for your feedback! I plan to start working on this once I have free time

**Comment by franzliedke** [comment]
I would love a helper for `select2_clear`.

**Comment by MatthewKennedy** [comment]
Hi @Hirurg103 ,

It would be useful to be able to click the remove x on pre-selected items in a multiple selector.

<img width="257" alt="Screenshot 2019-12-07 at 20 15 11" src="https://user-images.githubusercontent.com/1240766/70380223-8e503580-192f-11ea-864c-cfdd52983c48.png">

In the same way you have written the code to work across versions.

**Comment by KodyKendall** [comment]
Hey, this is a great idea! I'd use it today if it was done. Where is this currently at?

**Comment by Hirurg103** [comment]
Hi @KodyKendall , it is in progress now. I didn't push it yet

**Comment by Hirurg103** [comment]
Hi @coliver ,

in version `0.5.0` you can pass a string value the `search` parameter when you want to search for the different term than an option text:

```ruby
select2 'Buy milk', search: 'Buy'
```

[See this commit](https://github.com/Hirurg103/capybara_select2/commit/f669a72f933aa89f8a0659e07f03e201dfde32df) for the details
