### ISSUE TITLE
Selecting more than one select2 issue

### ISSUE THREAD

**Issue by MatthewKennedy** [Hirurg103/capybara_select2#17]
Hi,

When I run a test that selects options from several select2 dropdowns I get the following error:

`Selenium::WebDriver::Error::ElementClickInterceptedError:
       element click intercepted: Element <a href="javascript:void(0)" class="select2-choice select2-default" tabindex="-1">...</a> is not clickable at point (1119, 356). Other element would receive the click: <span title="...">Wed</span>
         (Session info: headless chrome=78.0.3904.70)`

Select2 v3.5

Is there a way round this?

If I just select one dropdown it works fine, but if I run 2 it throws up the error.

`select2 'cart', from: 'Status'`
  `select2 'paid', from: 'Payment State'`
  `click_on 'Filter Results'`

**Comment by MatthewKennedy** [comment]
I also found the same issue when using select2 v4.0

**Comment by Hirurg103** [comment]
Hi @MatthewKennedy , what browser are you using?

**Comment by MatthewKennedy** [comment]
I believe the tests run in the chrome browser, but I am out at the moment so I can’t confirm that 100% until I get in.

**Comment by MatthewKennedy** [comment]
The tests are running in chromedriver

**Comment by MatthewKennedy** [comment]
I believe the issue may of been when the tests written for an old version of Select2 tried to re-select an already selected item.

Tests seem to be working now using PR #20 and removing instances where tests were trying to select an already selected option.
