### ISSUE TITLE
"Capybara::ElementNotFound"

### ISSUE THREAD

**Issue by jacobwalkr** [Hirurg103/capybara_select2#21]
Hi there,

Just installed capybara-select-2. I'm generating a select2 from a grouped select:

```haml
= f.select(:for_programme_ids, Programme.grouped_options_for_select, {}, multiple: true, class: 'form-control select select2')
```

I'm trying to select an option:

```ruby
select2(project1.programmes[0].name, from: 'Programmes', search: true)
```

and getting this error:

```
Capybara::ElementNotFound: Unable to find css ".select2-results .select2-results__option[role='treeitem']" within #<Capybara::Node::Element tag="body" path="/HTML/BODY[1]">
```

I'm using CapybaraSelect2 0.4.2, Select2 4.0.12, Capybara 3.29.0, rspec-core 3.8.2, rspec-rails 3.8.3, Ruby 2.5.3 and Rails 5.2.3.

When I inspect the HTML, the options have `role="option"`, not `role="treeitem"`.

Any idea what the issue is or what to do about it?

Thanks :)

**Comment by jacobwalkr** [comment]
Currently working around it by redefining the OptionSelectors hash in `rails_helper.rb`:

```ruby
CapybaraSelect2::Selectors::OptionSelectors = {
    '2' => ".select2-container-active .select2-result",
    '3' => ".select2-drop-active .select2-result",
    '4' => ".select2-results .select2-results__option[role='option']"
  }.freeze
```

**Comment by MatthewKennedy** [comment]
Can you test out this PR #20

**Comment by jacobwalkr** [comment]
> Can you test out this PR #20

Seems to work for me! :)

Any reason you'd test an ARIA attribute over the role?

**Comment by MatthewKennedy** [comment]
Using the attribute `'4' => ".select2-results .select2-results__option[role]"` with no values set in the Grouped select box scenario picks up a duplicate element and fails the spec tests.

Using it with `'4' => ".select2-results .select2-results__option[role='option']"` fails in versions 4.0.8 and earlier.

**Comment by jacobwalkr** [comment]
Cool - well, your solution works for me!
