### ISSUE TITLE
Cannot select an option which happens to already be selected

### ISSUE THREAD

**Issue by Nerian** [Hirurg103/capybara_select2#22]
Hi,

See 

https://github.com/Hirurg103/capybara_select2/commit/53a9bf4a39d8d8e8ed0bda47fb01146994be086c#r36300327

I think the operation `select2 @manager.name, css: '.membership_contact_id'` should be idempotent; it should not matter if the option was already selected.

I believe we could fix this this changing line:

https://github.com/Hirurg103/capybara_select2/commit/53a9bf4a39d8d8e8ed0bda47fb01146994be086c#diff-ae92043bee3928497c5f6e5365d219bdL30-R30

to:

```
'4' => ".select2-results .select2-results__option"
```

**Comment by mashedkeyboard** [comment]
Also having this problem, would be great if this could be updated.

**Comment by Hirurg103** [comment]
> I think the operation select2 @manager.name, css: '.membership_contact_id' should be idempotent; it should not matter if the option was already selected.

I agree @Nerian . Will fix it asap
