### ISSUE TITLE
Does Not Seems to Have Support for `within`

### ISSUE THREAD

**Issue by hecvr** [Hirurg103/capybara_select2#23]
Let's say we have a form which requires users to fill fields for two comments. Each comment has the same set of fields, including a `Type` field which is a `select2` dropdown. Ideally, wrapping the `select2` call around `within` should do the trick but that's not happening.

The following snippet
```
within '#comment_1` do
  select2 'Note', from: 'Type'
end
```
results in the following error
```
Capybara::Ambiguous:
       Ambiguous match, found 2 elements matching visible css ".select2-results .select2-results__option[aria-selected='false']" within #<Capybara::Node::Element tag="body" path="/HTML/BODY[1]">
```
because there is another `Type` dropdown within `#comment_2`.

Seems to me, the problem is that the method referenced below does not takes `within` into consideration.
https://github.com/Hirurg103/capybara_select2/blob/c9481453dbe0dacf4f570c047ae3f7323da03b05/lib/capybara_select2/utils.rb#L20

Also, seems to be related to #1.

**Comment by hecvr** [comment]
I'm going to spend some time on this over the weekend.

**Comment by Hirurg103** [comment]
Hi, I guess you have two options containing word "Note"

Could you attach a screenshot of select2 element or html of it?

There is case that covers `within` functionality. Search on `within` in
`spec/shared/select2_spec.rb`

**Comment by hecvr** [comment]
@Hirurg103 , totally my bad. I was doing something wrong and rushed to open this issue. I'm closing it now.

**Comment by Hirurg103** [comment]
If you have several options with the same text you can use `match` option
(see Readme). For example

```
within '#comment_1' do
  select2 'Note', from: 'Type', match: :first
end
```
