### ISSUE TITLE
Thank You!!!

### ISSUE THREAD

**Issue by aualdrich** [Hirurg103/capybara_select2#25]
I don't really have an issue, but I just wanted to say thanks for making this and keeping it up to date. I recently updated select-2 and realized my tests started failing. I was delighted to see you had already addressed it in the new version of the gem. 

Feel free to close this issue. I just wan't sure where to say thanks!

**Comment by MatthewKennedy** [comment]
I want to second that, this is a brilliant gem thanks.

**Comment by Hirurg103** [comment]
Hello, @aualdrich, @MatthewKennedy 

Thank you Guys for the feedback! I'm glad that my work is useful

**Comment by rileytg** [comment]
Thank you!
