### ISSUE TITLE
Support for expectations

### ISSUE THREAD

**Issue by atd** [Hirurg103/capybara_select2#4]
What about helpers for asserting `select2` content?

Something like:

```
expect(select2(from: 'Things to do')).to have_content(['one', 'two', 'three'])
```

**Comment by Hirurg103** [comment]
Hi @atd , how about this syntax: `expect(page).to have_select2_option 'Things to do', label: 'Things to do'`

**Comment by atd** [comment]
It surely makes more sense

What about matching the array of selected options at once?

**Comment by Hirurg103** [comment]
I think that matching one option syntax will be enough. If you want to match two options you can type 

```ruby
expect(page).to have_select2_option 'Walk', label: 'Things to do'
expect(page).to have_select2_option 'Sleep', label: 'Things to do'
```

If you need to match many options you can do
```ruby
['walk', 'sleep', 'go to sym'].each do |option|
  expect(page).to have_select2_option option, label: 'Things to do'
end
```

You can add a PR with this RSpec matcher if you want

**Comment by Hirurg103** [comment]
@atd are you going to implement this feature or you want me to do it?

**Comment by Hirurg103** [comment]
Hi @atd I started wording on this enhancement
