### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by franzliedke** [Hirurg103/capybara_select2#8]
Thanks for this nice library. :)

Can I ask you to cut a new release - I am hoping that maybe changes on master fix some random crashes we're experiencing...

**Comment by Hirurg103** [comment]
Hi @franzliedke, thank for your feedback! I am happy that you use it!

> Can I ask you to cut a new release - I am hoping that maybe changes on master fix some random crashes we're experiencing...

I plan to do this in the short time, also would want to push some new additions and useful rspec matchers.

Could you provide more information what problems do you currently experience (error stack traces, capybara version, capybara driver and its version, Gemfile.lock)

Thank you

**Comment by franzliedke** [comment]
Awesome to hear, and no worries - take the time you need, I made sure I get notified of new releases. :)

> Could you provide more information what problems do you currently experience (capybara_select2 verison, error stack traces, capybara version, capybara driver and its version, Gemfile.lock). With that information it would be easier for me to make this gem more stable

It's one of those very hard-to-debug errors that occurs very rarely on our CI system.

    NoMethodError: undefined method `match' for nil:NilClass
    <backtrace empty>

That's literally the only error, but apparently the browser (Firefox) crashed - I saw that when watching our test run's recording.

Relevant versions:
- capybara (3.10.0)
- capybara-select-2 (0.3.2)
- selenium-webdriver (3.14.1)

**Comment by Hirurg103** [comment]
>  It's one of those very hard-to-debug errors that occurs very rarely on our CI system.
> ```
> NoMethodError: undefined method `match' for nil:NilClass
> <backtrace empty>
> ```

Thats interesting, I searched the source but could not find any occurrence of `match` in `0.3.2`  version. What version of select2 JS do you use?

The match option appears [in the master branch](https://github.com/Hirurg103/capybara_select2/blob/master/lib/capybara_select2/helpers.rb#L42)

It is sad that the error doesn't have any backtrace, I have no idea what is the source of the issue - capybara, selenium driver or the gem itself.

> Awesome to hear, and no worries - take the time you need, I made sure I get notified of new releases. :)

You can click on `Watch` in the right top corner of the gem homepage (if you want). I think that Github will automatically notify you about the new releases of the gem

**Comment by Hirurg103** [comment]
Hi @franzliedke ,

for now you can use the master branch of the gem from Github:

```
gem 'capybara-select-2', github: 'hirurg103/capybara_select2', group: :test
```

**Comment by Hirurg103** [comment]
Hi @franzliedke I've just pushed a new version of the gem. See version 0.4.0 on rubygems

**Comment by franzliedke** [comment]
Thanks a lot! :raised_hands:
